name: "Invoke-Build"
description: "Install specified version on Invoke-Build module and start build with Invoke-Build"
author: "Sergey.S.Betke@yandex.ru"
branding:
  icon: "package"
  color: blue
inputs:
  version:
    description: "InvokeBuild required version"
    required: false
    default: "latest"
  task:
    description: "build tasks"
    required: false
    default: "."
  file:
    description: "build file path"
    required: false
    default: "*.build.ps1"
  verbose:
    description: "verbose output"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - id: main
      shell: powershell
      run: |
        . "${{ github.action_path }}/Invoke-GitHubAction.ps1";
